name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  firebase_auth: ^5.3.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  english_words: ^4.0.0
  firebase_messaging: ^15.1.3
  provider: ^6.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  timeago: ^3.7.0
  flutter_animate: ^4.5.0
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  font_awesome_flutter: ^10.7.0
  path: ^1.9.0
  http: ^1.2.2
  bloc: ^8.1.4
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^18.0.0
  flutter_dotenv: ^5.2.1
  mobile_scanner: ^6.0.2
  audioplayers: ^6.1.0
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .dotenv
    - .env
    - assets/media/sounds/
    - assets/media/sounds/payment_success_1.mp3
    - assets/media/sounds/payment_success_2.mp3
    - assets/media/sounds/payment_success_3.mp3
    - assets/media/images/