// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7ngD9OEpopoM9f96FmkM0zqG4X8J-6M',
    appId: '1:495781403043:web:158da6df31cc27234ca216',
    messagingSenderId: '495781403043',
    projectId: 'cafetin-ibero-app',
    authDomain: 'cafetin-ibero-app.firebaseapp.com',
    storageBucket: 'cafetin-ibero-app.appspot.com',
    measurementId: 'G-E5C2NK0E2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIb3JwV4fjVAM9zcnLdMg6qhBKq8Aauw',
    appId: '1:495781403043:android:e16359bb6e61d2e24ca216',
    messagingSenderId: '495781403043',
    projectId: 'cafetin-ibero-app',
    storageBucket: 'cafetin-ibero-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneX7kCIdij8UkaycKFCXEbH-b_Ks7v-0',
    appId: '1:495781403043:ios:213fc1bbcf2603da4ca216',
    messagingSenderId: '495781403043',
    projectId: 'cafetin-ibero-app',
    storageBucket: 'cafetin-ibero-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCneX7kCIdij8UkaycKFCXEbH-b_Ks7v-0',
    appId: '1:495781403043:ios:213fc1bbcf2603da4ca216',
    messagingSenderId: '495781403043',
    projectId: 'cafetin-ibero-app',
    storageBucket: 'cafetin-ibero-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL7ngD9OEpopoM9f96FmkM0zqG4X8J-6M',
    appId: '1:495781403043:web:a24c192ebcea150d4ca216',
    messagingSenderId: '495781403043',
    projectId: 'cafetin-ibero-app',
    authDomain: 'cafetin-ibero-app.firebaseapp.com',
    storageBucket: 'cafetin-ibero-app.appspot.com',
    measurementId: 'G-KVBYD4BDH0',
  );
}